version = 1

[merge]
method = "squash"
delete_branch_on_merge = true
prioritize_ready_to_merge = true
notify_on_conflict = false
priority_merge_label = "priority-merge"
blocking_labels = ["DO-NOT-MERGE"]

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
