name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]'
    steps:
    - uses: hmarr/auto-approve-action@v3.2.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"