on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          git config --global user.email "nobody@atomic.io"
          git config --global user.name "Atomic Platform"
          git config --add push.autoSetupRemote true
      - run: yarn
      - if: ${{github.ref_name == 'main'}}
        name: create release version ${{github.ref}}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Actor ${{github.actor}}, event ${{ github.event_name }}"
          COMMIT_MSG=$(git show -s --format=%B '${{github.sha}}' | grep "^Release version" || echo "")
          if [ -n "${COMMIT_MSG}" ]; then
            echo "Don't need to create version here"
            exit 0
          fi

          PR_BRANCH_NAME=version-release-${{github.sha}}

          git checkout -b ${PR_BRANCH_NAME}

          ## do the release bump
          yarn version --new-version patch
          git diff
          git log

          NEW_VERSION=$(jq -r '.version' package.json)
          echo "VERSION: ${NEW_VERSION}"
          git push origin ${PR_BRANCH_NAME} && git push origin v${NEW_VERSION} && echo 'Bumped the version'

          gh pr create -B main -H ${PR_BRANCH_NAME} --label automerge --reviewer github-actions --title "Release version ${NEW_VERSION}" --body 'Created by Github action'
      - if: ${{github.ref_name == 'main' && github.actor == 'kodiakhq[bot]'}}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
