on:
  push:
    branches:
      - main
    tags:
      - v.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          git config --global user.email "nobody@atomic.io"
          git config --global user.name "Atomic Github Action"
      - run: yarn
      - if: github.ref_name == 'main'
        name: version release
        run: yarn version --new-version patch
      - if: startsWith( github.ref, 'refs/tags/v')
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  ## auto-approve for renovate
  auto-approve:
    if: github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
