on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          git config --global user.email "nobody@atomic.io"
          git config --global user.name "Atomic Platform"
          git config --add push.autoSetupRemote true
      - run: yarn
      - if: ${{github.ref_name == 'main'}}
        name: create release version ${{github.ref}}
        run: |
          echo "actor ${{github.actor}}"

          ## do the release bump
          yarn version --new-version patch
          NEW_VERSION=$( jq -r '.version' package.json)
          git checkout -b version-${NEW_VERSION}
          git status
          git log

          gh pr create -B main -H version-${NEW_VERSION} --title "Release version ${NEW_VERSION}" --body 'Created by Github action'
          ##git push && git push --tags && echo 'Bumped the version'
      # - if: ${{github.ref_name == 'main'}}
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
